version: "3.7"
services:
  app-dotnet-cntr:
    container_name: app-dotnet-cntr
    build: .
    ports:
      - "8080:8080"
    volumes:
      - C:\front-logger-volumes\front-logger-settings:/settings
    networks:
      - app-network
    depends_on:
      - postgres-cntr

  postgres-cntr:
    container_name: postgres-cntr
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - C:\front-logger-volumes\postgresql:/var/lib/postgresql
    networks:
      - app-network

  app-nginx-cntr:
    container_name: app-nginx-cntr
    image: nginx:1.17.6-alpine
    ports:
      - "80:80"
      - "443:443"
    tty: true
    entrypoint: /bin/sh
    command: -c "mv /etc/nginx/* /nginx && sleep 3 && rm -rf /etc/nginx && ln -sf /nginx /etc/nginx && nginx -g 'daemon off;'"
    volumes:
      - C:\front-logger-volumes\nginx-config:/nginx
    networks:
      - app-network
    depends_on:
      - app-dotnet-cntr

networks:
  app-network:
    driver: bridge