version: "3.7"
services:
  postgres-cntr:
    container_name: postgres-cntr
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - C:\teach-volumes\postgresql:/var/lib/postgresql
    networks:
      - teach-network

  dotnet-api-cntr:
    container_name: dotnet-api-cntr
    build: NetApi/.
    ports:
      - "8080:8080"
    volumes:
      - C:\teach-volumes\teach-net-settings:/settings
    networks:
      - teach-network
    depends_on:
      - postgres-cntr

  angular-app-cntr:
    container_name: angular-app-cntr
    build: AngularApp/.
    ports:
      - "4200:4200"
    volumes:
      - ./AngularApp:/app
    # entrypoint: /bin/bash
    # command: "-c 'sleep 3600'"
    networks:
      - teach-network
    depends_on:
      - dotnet-api-cntr

  nginx-teach-cntr:
    container_name: nginx-teach-cntr
    build: nginx/.
    ports:
      - "80:80"
      - "443:443"
    tty: true
    volumes:
      - ./nginx/conf:/nginx
    networks:
      - teach-network
    depends_on:
      - angular-app-cntr
    
networks:
  teach-network:
    driver: bridge