version: "3.7"
services:
  teach-app-angular:
    container_name: teach-app-angular
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    # entrypoint: /bin/bash
    # command: "-c 'sleep 3600'"
    networks:
      - teach-app-angular-network

networks:
  teach-app-angular-network:
    driver: bridge
